import { createSlice } from "@reduxjs/toolkit";

// const userSlice = createSlice({
//   name: "user", //? name of the slice
//   initialState: {
//     userData: undefined,
//   },
//   reducers: {
//     setUserData: (state, action) => {
//       state.userData = action.payload;
//     },
//   },
// });

const userSlice = createSlice({
  name: "user",
  initialState: {
    userData: null,
    loading: true,
    city: null,
  },
  reducers: {
    setUserData: (state, action) => {
      state.userData = action.payload;
      state.loading = false;
    },
    clearUser: (state) => {
      state.userData = null;
      state.loading = false;
    },
    setCity: (state, action) => {
      state.city = action.payload;
    },
  },
});

export const { setUserData, clearUser, setCity } = userSlice.actions; //? createSlice automatically generates action creators for each reducer function defined in the reducers object. By destructuring userSlice.actions, we can export these action creators (setUserData and clearUser) for use in our components to dispatch actions that will update the user state in the Redux store.

export default userSlice.reducer; //? for store configuration, we need to export the reducer function of the slice, which is generated by createSlice. This reducer will handle the actions defined in the reducers object and update the state accordingly.
